name: python_whl

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
          
      - name: download
        shell: cmd
        run: |          
          C:\msys64\usr\bin\wget.exe -nv -nc https://github.com/kawanakaiku/windows-ci/releases/download/python3/Python3.10.5.zip
          C:\msys64\usr\bin\unzip.exe -q Python3.10.5.zip
          
      - name: build wheel
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          
          mkdir windows-wheels
          cd Python310
          python.exe -m pip install -U pip
          python.exe -m pip install -U wheel setuptools
          python.exe -m pip wheel --wheel-dir ..\windows-wheels pyopenjtalk
          
      - name: Store whl files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: windows-wheels
          path: windows-wheels
          
      - name: Waiting for debugger
        if: failure()
        uses: mxschmitt/action-tmate@v3
