name: test

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      
      - name: Waiting for debugger
        if: always()
        uses: mxschmitt/action-tmate@v3
